name: Stable Branch - Push

on:
  push:
    branches: [stable]

env:
  NODE_OPTIONS: --max_old_space_size=4096
  AWS_REGION: eu-central-1
  BUILD_OVERRIDES: '{"tsConfig":{"compilerOptions":{"skipLibCheck":true}}}'

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      jest-packages: ${{ steps.list-jest-packages.outputs.jest-packages }}
      ts: ${{ steps.get-timestamp.outputs.ts }}
      webiny-version: ${{ steps.get-webiny-version.outputs.webiny-version }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/checkout@v3

      - name: Get current version of Webiny
        id: get-webiny-version
        run: echo "webiny-version=$(node --eval "console.log(require('./lerna.json').version)")" >> $GITHUB_OUTPUT

      - name: Get timestamp
        id: get-timestamp
        # run: echo "ts=$(node --eval "console.log(new Date().getTime())")" >> $GITHUB_OUTPUT
        run: echo "ts=$(node --eval "console.log(new Date().getTime())")" >> $GITHUB_OUTPUT

      - name: List packages with Jest tests
        id: list-jest-packages
        # run: echo "jest-packages=$(node scripts/listPackagesWithTests.js)" >> $GITHUB_OUTPUT
        run: echo "jest-packages=$(node scripts/listPackagesWithTests.js)" >> $GITHUB_OUTPUT

  build:
    needs: init
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v3
        id: cached-packages
        with:
          path: .webiny/cached-packages
          key: ${{ runner.os }}-${{ needs.init.outputs.webiny-version }}-${{ secrets.RANDOM_CACHE_KEY_SUFFIX }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' || steps.cached-packages.outputs.cache-hit != 'true'
        run: yarn --immutable

      - name: Build packages
        if: steps.cached-packages.outputs.cache-hit != 'true'
        run: node scripts/buildWithCache.js --build-overrides='${{ env.BUILD_OVERRIDES }}'

      - uses: actions/cache@v3
        id: packages-cache
        with:
          path: .webiny/cached-packages
          key: packages-cache-${{ needs.init.outputs.ts }}

  code-analysis:
    needs: [init, build]
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v3
        with:
          path: .webiny/cached-packages
          key: packages-cache-${{ needs.init.outputs.ts }}

      - name: Install dependencies
        run: yarn --immutable

      - name: Check code formatting
        run: yarn prettier:check

      - name: Check dependencies
        run: yarn adio

      - name: Check TS configs
        run: yarn check-ts-configs

      - name: ESLint
        run: yarn eslint

  #  code-analysis-typescript:
  #    name: Static code analysis (TypeScript)
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/setup-node@v3
  #        with:
  #          node-version: 14
  #
  #      - uses: actions/checkout@v3
  #
  #      - uses: actions/cache@v3
  #        with:
  #          path: .yarn/cache
  #          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
  #
  #      - name: Install dependencies
  #        run: yarn --immutable
  #
  #      - name: Build packages (full)
  #        run: node scripts/buildWithCache.js
  #
  #  jest-tests:
  #    needs: [init, build]
  #    name: ${{ matrix.package }} (${{ matrix.os }}, Node v${{ matrix.node }})
  #    strategy:
  #      fail-fast: false
  #      matrix:
  #        os: [ubuntu-latest]
  #        node: [14]
  #        package: ${{ fromJson(needs.init.outputs.jest-packages) }}
  #    runs-on: ${{ matrix.os }}
  #    env:
  #      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #      AWS_ELASTIC_SEARCH_DOMAIN_NAME: ${{ secrets.AWS_ELASTIC_SEARCH_DOMAIN_NAME }}
  #      ELASTIC_SEARCH_ENDPOINT: ${{ secrets.ELASTIC_SEARCH_ENDPOINT }}
  #      ELASTIC_SEARCH_INDEX_PREFIX: ${{ needs.init.outputs.ts }}_
  #    steps:
  #      - uses: actions/setup-node@v3
  #        with:
  #          node-version: ${{ matrix.node }}
  #
  #      - uses: actions/checkout@v3
  #
  #      - uses: actions/cache@v3
  #        with:
  #          path: .yarn/cache
  #          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
  #
  #      - name: Install dependencies
  #        run: yarn --immutable
  #
  #      - uses: actions/cache@v3
  #        with:
  #          path: .webiny/cached-packages
  #          key: packages-cache-${{ needs.init.outputs.ts }}
  #
  #      - name: Build packages
  #        run: node scripts/buildWithCache.js --build-overrides='${{ env.BUILD_OVERRIDES }}'
  #
  #      - name: Run tests
  #        run: yarn test ${{ matrix.package }}

  npm-release-beta:
    needs: [code-analysis]
    name: NPM release ("beta" tag)
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      BETA_VERSION: ${{ vars.BETA_VERSION }}
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v3
        with:
          path: .webiny/cached-packages
          key: packages-cache-${{ needs.init.outputs.ts }}

      - name: Install dependencies
        run: yarn --immutable

      - name: Build packages
        run: yarn build

      - name: Create ".npmrc" file in the project root
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

      - name: Set git email
        run: git config --global user.email "webiny-bot@webiny.com"

      - name: Set git username
        run: git config --global user.name "webiny-bot"

      - name: Version and publish "beta" tag to NPM
        run: yarn release --type=beta

  npm-release-latest:
    needs: npm-release-beta
    name: NPM release ("latest" tag)
    runs-on: ubuntu-latest
    environment: release
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      LATEST_VERSION: ${{ vars.LATEST_VERSION }}
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v3
        with:
          path: .webiny/cached-packages
          key: packages-cache-${{ needs.init.outputs.ts }}

      - name: Install dependencies
        run: yarn --immutable

      - name: Build packages
        run: yarn build

      - name: Create ".npmrc" file in the project root
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

      - name: Set git email
        run: git config --global user.email "webiny-bot@webiny.com"

      - name: Set git username
        run: git config --global user.name "webiny-bot"

      - name: Version and publish "latest" tag to NPM
        run: yarn release --type=latest
